### ISSUE TITLE
Allow horizontal split for markdown preview

### ISSUE THREAD

**Issue by zoomcharts** [madskristensen/WebEssentials2015#142]
I am using rotated monitors for work (1920px high, 1200px wide) and the markdown preview window is not really usable in its current form. If it could be split horizontally (below the source text) it would become much easier to use.

**Comment by thirdwaffle** [comment]
This would be handy for me too. I've got my editor window set up so that the code window is only about 140 characters wide (I try to keep all code within about 120 characters), so to have the markdown editor with the preview on the right side means I either have a really small editor, a really small preview or I have to resize all of the ancillary windows in Visual Studio (which I hate doing). Currently my workaround is to drag the markdown window out of Visual Studio and maximize it.

I've taken a look at the code, and it doesn't seem like it's that difficult to get the preview to resize top-to-bottom instead of left-to-right, *but* if I'm not mistaken, the preview is fixed to the right-side because of [the attribute that is applied to the margin factory](https://github.com/madskristensen/WebEssentials2015/blob/d5e06fc32291f3efcb8b1c4af7bd5835e715abc4/EditorExtensions/Shared/Margins/EditorMarginFactory.cs#L15). I'm not sure if this can be changed dynamically.

**Comment by ssg** [comment]
My case exactly. I have to disable preview because it becomes too narrow.

**Comment by madskristensen** [comment]
Fixed in the new Markdown Editor extension https://visualstudiogallery.msdn.microsoft.com/eaab33c3-437b-4918-8354-872dfe5d1bfe

(just added it so only available in the [CI build](http://vsixgallery.com/extension/9ca64947-e9ca-4543-bfb8-6cce9be19fd6/) until next release)
