### ISSUE TITLE
No jscs and JSHint support in WebEssentials 2015

### ISSUE THREAD

**Issue by Ciget** [madskristensen/WebEssentials2015#36]
Hi,

Could you please explain why in WebEssentials2015 has no JSHint and JSCS features?
Whould be nice to have it. If it`s obsolete - what should we use instead of it.

Thanks.

**Comment by SLaks** [comment]
You should use VS2015's native gulp or grunt integration.

**Comment by madskristensen** [comment]
Yep, this is by design

**Comment by misteroh** [comment]
@madskristensen I apologize... I know this isn't completely related but it seems from past experience GitHub is the fastest way to reach you/get a response rather than posting something on the Task Runner Visual Studio extension's official page on Visual Studio Gallery.

Will the Task runner or VS 2015's native integration ever be able to support a task that takes user input like https://github.com/Freyskeyd/gulp-prompt ?

Thank you so much for your time

**Comment by madskristensen** [comment]
@misteroh Not the standalone version for VS2013. We don't know yet how to do parameters for the Task Runner Explorer, but we'll probably find a way. It may come in an update to VS2015 but it won't be in the RTM version

**Comment by waynebloss** [comment]
This is unfortunate. I'd like my IDE to do the work for me instead of making me cobble together and maintain a gulpfile or whatever for each project.

Does anyone know of a working plugin that will give jshint ability back to VS2015?

**Comment by waynebloss** [comment]
Looks like the only available extension is [JSLint.NET](https://visualstudiogallery.msdn.microsoft.com/ede12aa8-0f80-4e6f-b15c-7a8b3499370e) but it's not jshint.

Any chance of getting a separate addon like the one created for issue #2?

**Comment by waynebloss** [comment]
For anyone else looking at this - I found a pretty simple solution that I like. I just want jshint on demand when I'm editing any old Javascript file, so I installed jshint with `> npm install -g jshint` and then I added it to Tools -> External Tools in Visual Studio like this:

![2015-07-12 13_55_30-external tools](https://cloud.githubusercontent.com/assets/623736/8639139/7bd802f6-289e-11e5-8c93-0f8ae0d03e2d.png)

and when I activate it, the output appears in the output window as specified in the External Tools dialog:

![2015-07-12 13_55_52-staticbuild vs2015 - microsoft visual studio](https://cloud.githubusercontent.com/assets/623736/8639150/afdf2ad4-289e-11e5-9a00-3e9bcb3cf698.png)

**Comment by rubenprins** [comment]
@madskristensen, I'm sorry, but this "design" is awful. Neither the task runner nor an external tool can replace the WE2013 JSHint integration. Simple things like 

* not having to press a key combination, write+run a task to get linter warnings
* using your error list, where other programming languages show their errors and warnings
* double clicking an error to open a file and go to the right line
* integration with squigglies and task-tips in the solution explorer with Productivity Power Tools

So no more open+click+fix, but now 

1. add the right packages to your project.json
2. define a grunt task (a separate task per .js file if you want to be able to cope with the flood of errors if you inherit files from other people not used to linters)
3. search Google to find out what the heck the right task declaration options are
4. open the task runner explorer
5. refresh the task runner explorer to pick up the changes to the gruntfile
6. run the task
7. goto 3
8. scroll back to the top of the task output window
9. take note of the file name and line number
10. open the file
11. Ctrl+G to fill in the line number
12. give up.

Losing these features for me is a huge dent in my productivity. So much so, that I'm currently not even considering upgrading to VS+WE 2015 for any JavaScript development.

LESS and bundling appear to be making a comeback, but I have seen no such reassurances for linting.

VS+WE used to be a web IDE, as in **Integrated** development enviroment. Right now VS 2015 is not much more than a dozen unrelated console output windows.

**Comment by markbedeker** [comment]
:+1:

**Comment by waynebloss** [comment]
JSLint is way too opinionated for me or else I would have just used the JSLint.NET extension.

Is there anyone who knows the code-base willing to pull the code out of the WE2013 and make a separate extension similar to what was done for the LESS and bundling features? If not, maybe I'll take a look.

**Comment by waynebloss** [comment]
@madskristensen Would you or someone on your team of volunteers be willing to make at least a prototype of a separate extension, so that we can run JSHint like we were able to in the past? Even if you don't maintain it, it would be a good start for someone who did.

Alternatively, would you mind telling me if it's a real PITA to do or not? I will consider digging around in there and getting it started. I have some experience building addons for VS and also MEF which I believe is now being used by VS in some capacity, for extensions.

Personally, I would settle for a JSHint extension shows me clickable errors in my error list, that I can activate with a hotkey. I don't need the squiggly red underlines or smart-tags personally and if they're difficult to do we could add that back into the new JSHint extension for a 2.0 release or something.

**Comment by madskristensen** [comment]
My plans is to build a separate extension for that, but haven't gotten around to it yet. The jslint extension allows you to configure the rules I believe

**Comment by rubenprins** [comment]
@madskristensen, I'm happy to hear JSHint is not forgotten. Great news.

And if you could make JSCS and JSHint linting into separate extensions, or make a toggle for them, I'd be even happier. (Not a fan of JSCS, love JSHint.)

@waynebloss, The squigglies and smart-tags I'm referring to are the squigglies and tooltips Productivity Power Tools infers from the Error List (and only applies to the solution explorer tree). As long as the Error List is filled, and has the proper file name and line numbers, this works automatically.

I don't mind if the text editor doesn't squiggle or provide tooltips/smart tags. It doesn't do that in WE2013 either, and that would probably a lot more effort on Mads' part. I've never missed it (never even though of it before, to be honest).

**Comment by philippejer** [comment]
Extending on Wayne Bloss workaround using external tools (the JSLint plugin does not accept JSHint options as far as I can see):

To get VS to recognize the line numbers in the output window, I have had success using a quick&dirty wrapper command to reformat the JSHint output (needs some version of sed in the path):

```
:: call JSHint and reformat the output so that VS can jump to the correct line
@jshint %* | sed "s/\(.*\): line \([0-9]\+\), col \([0-9]\+\), \(.*\)/\1(\2,\3): \4/"
```

**Comment by waynebloss** [comment]
Thanks @philippejer - it works really well. Also, you can use the full path to sed that will probably work everywhere Git for Windows is installed -

```
:: call JSHint and reformat the output so that VS can jump to the correct line
@jshint %* | "C:\Program Files\Git\usr\bin\sed.exe" -e "s/\(.*\): line \([0-9]\+\), col \([0-9]\+\), \(.*\)/\1(\2,\3): \4/"
```

**Comment by jMichaelNet** [comment]
Thank you @waynebloss and @philippejer.  Everytime I go away for a few months and return, everything good has been taken away.  :)   Just...why?  For those who have not written any Windows commands since forever, I created a MyJsHint.cmd in the same dir as the jshint.cmd, and inserted Wayne's command, and finally used MyJsHint.cmd instead of jshint.cmd for the VS External Tools command.  Which is exactly what Phillip described and seems obvious in retrospect.  Life is good again!

**Comment by k3ilbasa** [comment]
@waynebloss, @philippejer  where does this command go?  Have you found a better solution for this issue yet?

> Thanks @philippejer - it works really well. Also, you can use the full path to sed that will probably work everywhere Git for Windows is installed -
:: call JSHint and reformat the output so that VS can jump to the correct line
@jshint %* | "C:\Program Files\Git\usr\bin\sed.exe" -e "s/\(.*\): line \([0-9]\+\), col \([0-9]\+\)

**Comment by madskristensen** [comment]
Use Web Analyzer https://visualstudiogallery.msdn.microsoft.com/6edc26d4-47d8-4987-82ee-7c820d79be1d

**Comment by Paszt** [comment]
Installing Web Analyzer gives you a warning to uninstall it and install .NET Core Tooling Preview instead, so skip installing Web Analyzer.
