### ISSUE TITLE
Add support for .d.ts files in JavaScript 

### ISSUE THREAD

**Issue by svenvNL** [madskristensen/WebEssentials2015#52]
In Visual Studio Code JavaScript Intellisense can be extended by using .d.ts files. Code also suggests to use a particular file when it doesn't have Intellisense.

Would it be possible to add this future by adding files from borisyankov/DefinitelyTyped ? I am talking about the JavaScript editor. Not the TypeScript editor.

**Comment by madskristensen** [comment]
Unfortunately not through WE. Only the js team in VS can add the support

**Comment by svenvNL** [comment]
@madskristensen just curious, why is it possible to use JavaScript files from schemastore.org that deliver JavaScript intellisense like for Angular, etc but not .d.ts files?

**Comment by aikeru** [comment]
@svenvNL the simplest answer is that TypeScript is not JavaScript and the TypeScript tooling is separate from the JavaScript tooling. Why would you expect the JavaScript editor to understand TypeScript interfaces (and classes) that are not JavaScript? That would be a neat trick, though.

The files on schemastore like ```angular.intellisense.js``` are pure JavaScript files. They are not TypeScript.

It may be possible for you to use ```<reference />``` tags against the generated JavaScript files, but they will not be able to use the TypeScript-based meta information (ie: compile-time type info) and due to the way TypeScript generates certain generated code may be too dynamic to get any intellisense help at all.
