### ISSUE TITLE
TypeSciprt Editor : Javascript Preview Pane Not Visible

### ISSUE THREAD

**Issue by ankeshdave** [madskristensen/WebEssentials2015#53]
I am not able to See JavaScript Preview pane (Also not able to find the option) in VS 2015 RC :disappointed: .  
Also, I am not able to find "Show Preview Pane Options" in Tools->Options menu. 
**Screenshot :** 
![** Screenshot](https://cloud.githubusercontent.com/assets/1351658/8036139/81c183a4-0e13-11e5-8920-3ebf0c08b12f.png)

**Installation Details :**   
1) VS 2015 RC
2) Web Essentials   : 2015 RC v0.4.118
3) Offiicial TS Tools : TypeScript 1.5beta for VS2015

Any specific steps required to enable preview  :smile: .

**Comment by madskristensen** [comment]
The TS preview pane has been removed from Web Essentials 2015 due to continuously running into conflicts with the TS compiler when new versions come out. The TS team are aware of it and I hope they will make a fix. It is possible that this feature will be included in the brand new Web Compiler extensions (https://visualstudiogallery.msdn.microsoft.com/3b329021-cd7a-4a01-86fc-714c2d05bb6c) when preview panes have been implemented.

**Comment by abukres** [comment]
Please add this fact/warning to your typescript page. I just spent unnecessary time trying to find out why I am not getting the preview pane. http://vswebessentials.com/features/typescript#

**Comment by richhosek** [comment]
More than a year later, and the Web Essentials page still shows the preview pane as a feature.
Also, it used to be that the .js and .map files were added as part of the project you could see them and add them with drag and drop to your html files. This no longer seems to be the case. Am I missing a setting?

**Comment by ViRuSTriNiTy** [comment]
Same here, searching why i don't get a preview pane for hours now and finally stackoverflow brought me here. Please, just bring back the feature and add an option to enable the pane. It was a killer feature, why would you remove it completely, i don't understand.
